# Generated by Django 4.2.5 on 2023-10-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_alter_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
